### PR TITLE
Fixed issue with current timestamp key instead of former timestampMs.…

### PR DESCRIPTION
**Pull request by motophil**
Fixed issue with current timestamp key instead of former timestampMs. 
Works with old and new version of takeout.
ToDo: fix chronological.
Based on the contribution of @rickprice, included in this pull request with his permission (thanks!)

### CODE REVIEW

**Comment by Scarygami** [comment]
Hi, thanks a lot for preparing this PR. I noticed that you have an open Todo in there for the sorted/chronological option. Would it be possible for you to implement this todo before I merge the PR?

**Comment by motophil** [comment]
Hi Gerwin,

I didn't look into it at first since my Python is a bit rusty, but looking into it a pythonic fix was pretty easy. So: Fixed.

- Philip

**Comment by dfmore** [comment]
@Scarygami the fix proposed here worked for me

**Comment by Scarygami** [comment]
Thanks for working on this and sorry for the delay in merging.

**Pull request merged**
